/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaaplicaciónleydeohm;

/**
 *
 * @author Usuario
 *//**
 *
 * @author Usuario
 *//**
 *
 * @author Usuario
 *//**
 *
 * @author Usuario
 *//**
 *
 * @author Usuario
 */
public class InterfazGráfica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGráfica
     */
    public InterfazGráfica() {
        initComponents();
        
        this.setLocationRelativeTo(null);//Pa' que la ventana aparezca desde el centro
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotVolt = new javax.swing.JButton();
        BotAmp = new javax.swing.JButton();
        BotRes = new javax.swing.JButton();
        BotPot = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 70, 25));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaaplicaciónleydeohm/Imagenes/Circuito1a.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 210, 180));

        BotVolt.setBackground(new java.awt.Color(0, 0, 51));
        BotVolt.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BotVolt.setForeground(new java.awt.Color(153, 255, 255));
        BotVolt.setText("Voltaje (V)");
        BotVolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotVoltActionPerformed(evt);
            }
        });
        getContentPane().add(BotVolt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 160, 50));

        BotAmp.setBackground(new java.awt.Color(0, 0, 51));
        BotAmp.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BotAmp.setForeground(new java.awt.Color(153, 255, 255));
        BotAmp.setText("Amperaje (I)");
        BotAmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAmpActionPerformed(evt);
            }
        });
        getContentPane().add(BotAmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 160, 50));

        BotRes.setBackground(new java.awt.Color(0, 0, 51));
        BotRes.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BotRes.setForeground(new java.awt.Color(153, 255, 255));
        BotRes.setText("Resistencia (Ω)");
        BotRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotResActionPerformed(evt);
            }
        });
        getContentPane().add(BotRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 160, 50));

        BotPot.setBackground(new java.awt.Color(0, 0, 51));
        BotPot.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        BotPot.setForeground(new java.awt.Color(153, 255, 255));
        BotPot.setText("Potencia (W)");
        BotPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotPotActionPerformed(evt);
            }
        });
        getContentPane().add(BotPot, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 160, 50));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setText("Calculadora Ley de Ohm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("¿Qué quieres calcular?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 255, 255));
        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 70, 25));
        jButton2.getAccessibleContext().setAccessibleName("Instrucciones");

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaaplicaciónleydeohm/Imagenes/Fondo1a.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 548));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotVoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotVoltActionPerformed
        // TODO add your handling code here:
        JFrame_Voltaje abrir = new JFrame_Voltaje();
        abrir.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BotVoltActionPerformed

    private void BotAmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAmpActionPerformed
        // TODO add your handling code here:
        JFrame_Amperaje abrir = new JFrame_Amperaje();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotAmpActionPerformed

    private void BotResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotResActionPerformed
        // TODO add your handling code here:
        JFrame_Resistencia abrir = new JFrame_Resistencia();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotResActionPerformed

    private void BotPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotPotActionPerformed
        // TODO add your handling code here:
        JFrame_Potencia abrir = new JFrame_Potencia();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotPotActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame_Ayuda abrir = new JFrame_Ayuda();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGráfica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAmp;
    private javax.swing.JButton BotPot;
    private javax.swing.JButton BotRes;
    private javax.swing.JButton BotVolt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
