/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaaplicaciónleydeohm;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author Usuario
 */
public class JFrame_Resistencia extends javax.swing.JFrame {
    Resistencia OperarRes = new Resistencia();
    /**
     * Creates new form JFrame_Resistencia
     */
    public JFrame_Resistencia() {
        initComponents();
        this.setLocationRelativeTo(null); //La ventana sale desde el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RVolt = new javax.swing.JTextField();
        RAmp = new javax.swing.JTextField();
        RPot = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CalcularRes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RResultado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tensión (V)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Intensidad (A)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Potencia (W)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        RVolt.setBackground(new java.awt.Color(255, 153, 0));
        RVolt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        RVolt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RVoltKeyTyped(evt);
            }
        });
        getContentPane().add(RVolt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 280, 30));

        RAmp.setBackground(new java.awt.Color(255, 153, 0));
        RAmp.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        RAmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAmpActionPerformed(evt);
            }
        });
        RAmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RAmpKeyTyped(evt);
            }
        });
        getContentPane().add(RAmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 280, 30));

        RPot.setBackground(new java.awt.Color(255, 153, 0));
        RPot.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        RPot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RPotKeyTyped(evt);
            }
        });
        getContentPane().add(RPot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 280, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        CalcularRes.setBackground(new java.awt.Color(204, 204, 204));
        CalcularRes.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        CalcularRes.setForeground(new java.awt.Color(255, 153, 0));
        CalcularRes.setText("Calcular");
        CalcularRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularResActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 90, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Calculadora de Resistencia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        RResultado.setBackground(new java.awt.Color(255, 102, 0));
        RResultado.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        RResultado.setOpaque(true);
        getContentPane().add(RResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 280, 30));

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Resultado(Ω)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 153, 0));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 90, 30));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("V= voltios, A= amperios, Ω= Ohmios, W= vatios.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaaplicaciónleydeohm/Imagenes/ResistenciaFondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RAmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAmpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InterfazGráfica atrás = new InterfazGráfica();
        atrás.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame_Resistencia borrar = new JFrame_Resistencia();
        borrar.setVisible(true);
        RVolt.removeAll();
        RAmp.removeAll();
        RPot.removeAll();
        RResultado.removeAll();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CalcularResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularResActionPerformed
        // TODO add your handling code here:
        if ( RVolt.getText().length()>0 
        &&  RAmp.getText().length() >0 
                && RPot.getText().length()==0 )
        {
        double Volt = Double.parseDouble(RVolt.getText());
        double Amp = Double.parseDouble(RAmp.getText());
        OperarRes.CálculoResistencia(Volt,Amp);
         RPot.setText("-");
         RResultado.setText(Double.toString(OperarRes.Res));
        } else if (RVolt.getText().length()>0 
                &&  RPot.getText().length()>0 
                && RAmp.getText().length()==0)
        {
        double Volt = Double.parseDouble(RVolt.getText());
        float Pot = (float) Double.parseDouble(RPot.getText());
        OperarRes.CálculoResistencia(Volt,Pot);
        RAmp.setText("-");
        RResultado.setText(Double.toString(OperarRes.Res));
        } else if (RPot.getText().length()>0 
                &&  RAmp.getText().length()>0 
                && RVolt.getText().length()==0)
        {
        float Pot = (float) Double.parseDouble(RPot.getText());
        double Amp = Double.parseDouble(RAmp.getText());
        OperarRes.CálculoResistencia(Pot,Amp);
        RVolt.setText("-");
        RResultado.setText(Double.toString(OperarRes.Res));
        
        }
        else{JOptionPane.showMessageDialog(rootPane, "Error");}
              
                
        RResultado.setText(Double.toString(OperarRes.Res));
    }//GEN-LAST:event_CalcularResActionPerformed

    private void RVoltKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RVoltKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  RVolt.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        }
    }//GEN-LAST:event_RVoltKeyTyped

    private void RAmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RAmpKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  RAmp.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        }
    }//GEN-LAST:event_RAmpKeyTyped

    private void RPotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RPotKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  RPot.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        }
    }//GEN-LAST:event_RPotKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Resistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Resistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Resistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Resistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Resistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularRes;
    private javax.swing.JTextField RAmp;
    private javax.swing.JTextField RPot;
    private javax.swing.JLabel RResultado;
    private javax.swing.JTextField RVolt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
