/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaaplicaciónleydeohm;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;


/**
 *
 * @author Usuario
 */
public class JFrame_Potencia extends javax.swing.JFrame {
Potencia OperarPot = new Potencia();
    /**
     * Creates new form JFrame_Potencia
     */
    public JFrame_Potencia() {
        initComponents();
        this.setLocationRelativeTo(null); //La ventana sale desde el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        CalcularPot = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PVolt = new javax.swing.JTextField();
        PAmp = new javax.swing.JTextField();
        PRes = new javax.swing.JTextField();
        PResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        CalcularPot.setBackground(new java.awt.Color(153, 153, 153));
        CalcularPot.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        CalcularPot.setForeground(new java.awt.Color(51, 0, 51));
        CalcularPot.setText("Calcular");
        CalcularPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularPotActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularPot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 90, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 0, 51));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 90, 30));

        PVolt.setBackground(new java.awt.Color(102, 0, 102));
        PVolt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        PVolt.setForeground(new java.awt.Color(255, 255, 255));
        PVolt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PVoltKeyTyped(evt);
            }
        });
        getContentPane().add(PVolt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 280, 30));

        PAmp.setBackground(new java.awt.Color(102, 0, 102));
        PAmp.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        PAmp.setForeground(new java.awt.Color(255, 255, 255));
        PAmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PAmpKeyTyped(evt);
            }
        });
        getContentPane().add(PAmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 280, 30));

        PRes.setBackground(new java.awt.Color(102, 0, 102));
        PRes.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        PRes.setForeground(new java.awt.Color(255, 255, 255));
        PRes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PResKeyTyped(evt);
            }
        });
        getContentPane().add(PRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 280, 30));

        PResultado.setBackground(new java.awt.Color(51, 0, 102));
        PResultado.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        PResultado.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 280, 30));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tensión (V)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Intensidad (A)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resistencia (Ω)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Resutado (W)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Calculadora de Potencia");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("V= voltios, A= amperios, Ω= Ohmios, W= vatios.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaaplicaciónleydeohm/Imagenes/PotenciaFondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InterfazGráfica atrás = new InterfazGráfica();
        atrás.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CalcularPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularPotActionPerformed
        // TODO add your handling code here:
        if ( PVolt.getText().length()>0 
        &&  PAmp.getText().length() >0 
                && PRes.getText().length()==0 )
        {
        double Volt = Double.parseDouble(PVolt.getText());
        double Amp = Double.parseDouble(PAmp.getText());
        OperarPot.CálculoPotencia(Volt,Amp);
         PRes.setText("-");
         PResultado.setText(Double.toString(OperarPot.Pot));
        } else if (PAmp.getText().length()>0 
                &&  PRes.getText().length()>0 
                && PVolt.getText().length()==0)
        {
        double Amp = Double.parseDouble(PAmp.getText());
        float Res = (float) Double.parseDouble(PRes.getText());
        OperarPot.CálculoPotencia(Amp,Res);
        PVolt.setText("-");
        PResultado.setText(Double.toString(OperarPot.Pot));
        } else if (PRes.getText().length()>0 
                &&  PVolt.getText().length()>0 
                && PAmp.getText().length()==0)
        {
        float Res = (float) Double.parseDouble(PRes.getText());
        double Volt = Double.parseDouble(PVolt.getText());
        OperarPot.CálculoPotencia(Res,Volt);
        PAmp.setText("-");
        PResultado.setText(Double.toString(OperarPot.Pot));
        
        }
        else{JOptionPane.showMessageDialog(rootPane, "Error");}
              
                
        PResultado.setText(Double.toString(OperarPot.Pot));
    }//GEN-LAST:event_CalcularPotActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         JFrame_Potencia borrar = new JFrame_Potencia();
        borrar.setVisible(true);
        PVolt.removeAll();
        PAmp.removeAll();
        PRes.removeAll();
        PResultado.removeAll();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PVoltKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PVoltKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  PVolt.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
                
                }
       
    }//GEN-LAST:event_PVoltKeyTyped

    private void PAmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PAmpKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  PAmp.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
                
                }
       
    }//GEN-LAST:event_PAmpKeyTyped

    private void PResKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PResKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  PRes.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
                
                }
       
    }//GEN-LAST:event_PResKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Potencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Potencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularPot;
    private javax.swing.JTextField PAmp;
    private javax.swing.JTextField PRes;
    private javax.swing.JTextField PResultado;
    private javax.swing.JTextField PVolt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
