/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaaplicaciónleydeohm;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class JFrame_Amperaje extends javax.swing.JFrame {
Amperaje OperarAmp = new Amperaje();
    /**
     * Creates new form JFrame_Amperaje
     */
    public JFrame_Amperaje() {
        initComponents();
        this.setLocationRelativeTo(null); //La ventana sale desde el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AVolt = new javax.swing.JTextField();
        APot = new javax.swing.JTextField();
        ARes = new javax.swing.JTextField();
        CalcularAmp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        AResultado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Atrás");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tensión (V)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Resistencia (Ω)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Potencia (W)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        AVolt.setBackground(new java.awt.Color(0, 102, 102));
        AVolt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        AVolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVoltActionPerformed(evt);
            }
        });
        AVolt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AVoltKeyTyped(evt);
            }
        });
        getContentPane().add(AVolt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 280, 30));

        APot.setBackground(new java.awt.Color(0, 102, 102));
        APot.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        APot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                APotKeyTyped(evt);
            }
        });
        getContentPane().add(APot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 280, 30));

        ARes.setBackground(new java.awt.Color(0, 102, 102));
        ARes.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        ARes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AResKeyTyped(evt);
            }
        });
        getContentPane().add(ARes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 280, 30));

        CalcularAmp.setBackground(new java.awt.Color(0, 0, 0));
        CalcularAmp.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        CalcularAmp.setForeground(new java.awt.Color(204, 255, 255));
        CalcularAmp.setText("Calcular");
        CalcularAmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularAmpActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularAmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 90, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Calculadora de Amperaje");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        AResultado.setBackground(new java.awt.Color(0, 51, 102));
        AResultado.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        AResultado.setOpaque(true);
        getContentPane().add(AResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 280, 30));

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Resultado (A)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 255));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 90, 30));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("V= voltios, A= amperios, Ω= Ohmios, W= vatios.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaaplicaciónleydeohm/Imagenes/AmperajeFondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AVoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVoltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AVoltActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InterfazGráfica atrás = new InterfazGráfica();
        atrás.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame_Amperaje borrar = new JFrame_Amperaje();
        borrar.setVisible(true);
        AVolt.removeAll();
        APot.removeAll();
        ARes.removeAll();
        AResultado.removeAll();
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CalcularAmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularAmpActionPerformed
        // TODO add your handling code here:
        
        if ( AVolt.getText().length()>0 
        &&  ARes.getText().length() >0 
                && APot.getText().length()==0 )
        {
        double Volt = Double.parseDouble(AVolt.getText());
        double Res = Double.parseDouble(ARes.getText());
        OperarAmp.CálculoAmperaje(Volt,Res);
         APot.setText("-");
         AResultado.setText(Double.toString(OperarAmp.Amp));
        } else if (AVolt.getText().length()>0 
                &&  APot.getText().length()>0 
                && ARes.getText().length()==0)
        {
        double Volt = Double.parseDouble(AVolt.getText());
        float Pot = (float) Double.parseDouble(APot.getText());
        OperarAmp.CálculoAmperaje(Volt,Pot);
        ARes.setText("-");
        AResultado.setText(Double.toString(OperarAmp.Amp));
        } else if (APot.getText().length()>0 
                &&  ARes.getText().length()>0 
                && AVolt.getText().length()==0)
        {
        float Pot = (float) Double.parseDouble(APot.getText());
        double Res = Double.parseDouble(ARes.getText());
        OperarAmp.CálculoAmperaje(Pot,Res);
        ARes.setText("-");
        AResultado.setText(Double.toString(OperarAmp.Amp));
        
        }
        else{JOptionPane.showMessageDialog(rootPane, "Error");}
              
                
        AResultado.setText(Double.toString(OperarAmp.Amp));
        
    }//GEN-LAST:event_CalcularAmpActionPerformed

    private void AVoltKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AVoltKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  AVolt.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        }
    }//GEN-LAST:event_AVoltKeyTyped

    private void AResKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AResKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  ARes.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        }
    }//GEN-LAST:event_AResKeyTyped

    private void APotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_APotKeyTyped
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        //condición que nos permite ingresar datos numéricos con su punto decimal
        if ((var<'0' || var >'9')&&  APot.getText().contains(".")
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        } else if ((var < '0' || var > '9') && (var!= '.') 
                && (var!=(char)KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
        JOptionPane.showMessageDialog(null, "Sólo se admiten números");
        }
    }//GEN-LAST:event_APotKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Amperaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Amperaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Amperaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Amperaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Amperaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APot;
    private javax.swing.JTextField ARes;
    private javax.swing.JLabel AResultado;
    private javax.swing.JTextField AVolt;
    private javax.swing.JButton CalcularAmp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
